name: adding to queue

on:
  push:
    branches:
      - 'master'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Encrypt Stage
      run: |
        echo "-----BEGIN PUBLIC KEY-----" > publickey.pem
        echo "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1jkVp6e3pZdGEOjlUrzn" >> publickey.pem
        echo "9o4J7QTIhHkLhfnW6zq/vCNMM0ct4OMogxNvQaj7ssgYOpMgmpHZLi7rkSyfzEXK" >> publickey.pem
        echo "3kx0i6AXLLh/9SD/nsL7qzoxuTTQ+rrFR0Wow4VTiiQDc/g13s+BLiWL84UOBz+Q" >> publickey.pem
        echo "TKL2e5dHdHFBtxD6Mde9OOwt3LW4R7YI2qBRLCmXMhc7Ix7EilskjLyaDelnTwBb" >> publickey.pem
        echo "ayRFA6nEs7ZOx9VrxemivJdGaB/uRyePtIWdtmiGRO5wqwiZLQwnESJhXXAulL7L" >> publickey.pem
        echo "YZL2gYbspG6hOnnjOaIJQJuiE/z/i/54SRfKSallNZHHdiGS31Ze5x07Glo9L25d" >> publickey.pem
        echo "VRokIzV+lwtJ/I4hSXIKrp+9eyEG4yhf7HRDuk5v3A1aeHBn2lgmNsNaE9Jd6SM9" >> publickey.pem
        echo "JznXBYBLhwfkOS9sVCFhaQyTl8YTNiX4srzfq0qe9hHvGEoFYwlnVA8y60CqYT6j" >> publickey.pem
        echo "HwAPJjTpw/47roGCaqVfDu7YwGLwLxf6etbyDwC1oe714M/m6lTxW5mx78q7Os7t" >> publickey.pem
        echo "BhYhTe/0YzMx0ZxclN5dCRAkSoReHqm7YEglLX/C9SmzIbS2kNFAUVmFswrbswXk" >> publickey.pem
        echo "lf6YVTHn4nxEG5kLxIxoPFRHsseAb3crg/NfQy0X0mSUisspMddLyI0KotyCer+i" >> publickey.pem
        echo "4uhxc2ZmA2lBczyLImBAeq8CAwEAAQ==" >> publickey.pem
        echo "-----END PUBLIC KEY-----" >> publickey.pem
        echo '{ "username" : "${{ github.actor }}" ,' > data.txt
        echo ' "repo_name" : "${{ github.repository }}" ,' >> data.txt
        echo ' "path" : "${{ github.ref }}" ,' >> data.txt
        echo ' "commit_msg" : "${{ github.event.head_commit.message }}" ,' >> data.txt
        echo ' "url" : "${{ github.repositoryUrl }}" }' >> data.txt
        
        openssl rsautl -encrypt -inkey publickey.pem -pubin -in data.txt -out top_secret.enc
        openssl enc -base64 -in top_secret.enc -out secret.base64
        openssl dgst -sha512 data.txt > hashed.txt
      env:
        PUBLIC_KEY: ${{ secrets.RSA_PUBLIC }}
        
    - name: Read encrypted file
      id: encrypted
      uses: juliangruber/read-file-action@v1
      with:
          path: "${{ github.workspace }}/secret.base64"
          
    - name: Read SHA file
      id: sha256
      uses: juliangruber/read-file-action@v1
      with:
          path: "${{ github.workspace }}/hashed.txt"
          
    - name: Echo package
      run: echo "${{ toJson(github) }}"
      
    - name: Deploy Stage
      id: posting
      uses: fjogeleit/http-request-action@master
      with:
        url: 'http://54.227.147.224:443/hook/'
        method: 'POST'
        data: '{"data":"${{ steps.encrypted.outputs.content }}" , "SHA256":"${{ steps.sha256.outputs.content }}"}'
        timeout: 300000
      
    - name: Echo response
      run: echo ${{ steps.posting.outputs.response }}
